name: Run Tests
on: push
jobs:
  run-all-tests:
    runs-on: ubuntu-latest
    env:
      NEXT_AUTH_GITHUB_ID: ${{ secrets.NEXT_AUTH_GITHUB_ID }}
      NEXT_AUTH_GITHUB_SECRET: ${{ secrets.NEXT_AUTH_GITHUB_SECRET }}
      NEXTAUTH_URL: ${{ secrets.NEXTAUTH_URL }}
      NEXTAUTH_SECRET: ${{ secrets.NEXTAUTH_SECRET }}

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up Node 21
        uses: actions/setup-node@v3
        with:
          node-version: 21

      - name: Install Dependencies
        run: yarn install

      - name: Install Playwright Browsers
        run: npx playwright install

      - name: Run Playwright Tests
        run: npm run test

      - name: Run Jest Tests
        run: npm run jest:test
